config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :parties
  resources :pokemons
  resources :trainers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/party.rb
class Party < ApplicationRecord
    belongs_to :trainer
    has_many :party_pokemons
    has_many :pokemons, through: :party_pokemons
    
    validates :name, presence: true


end

app/models/party_pokemon.rb
class PartyPokemon < ApplicationRecord
    belongs_to :pokemon
    belongs_to :party
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :party_pokemons
    has_many :parties, through: :party_pokemons
    belongs_to :species

    validates :nickname, uniqueness: true

    def self.create_pokemon(pokemon_params)
    
        @species = Species.find(pokemon_params["species_id"].to_i)
        
        species_page = RestClient.get(@species.url)
        species_info = JSON.parse(species_page)
        
        #Types
        species_types = species_info["types"]
        types_array = []
        species_types.each do |slot|
            types_array << slot["type"]["name"]
        end
        if types_array.length == 2
            @pokemon = Pokemon.create(
                nickname: pokemon_params["nickname"].capitalize,
                species_id: pokemon_params["species_id"].to_i,
                type_1: types_array[0].capitalize,
                type_2: types_array[1].capitalize
            )
        else
            @pokemon = Pokemon.create(
                nickname: pokemon_params["nickname"].capitalize,
                species_id: pokemon_params["species_id"].to_i,
                type_1: types_array[0].capitalize,
                type_2: types_array[1]
            )
        end
    end
end

app/models/species.rb
class Species < ApplicationRecord
    has_many :pokemons
    
    def self.get_data
        species_list = RestClient.get 'https://pokeapi.co/api/v2/pokemon?&limit=151'
        species_array = JSON.parse(species_list)["results"]
        species_array.each do |species|
            species_page = RestClient.get(species["url"])
            species_info = JSON.parse(species_page)
            #Default name and URL
            species = self.create(name: species["name"], url: species["url"])
        end
    end
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :parties
    has_many :pokemon, through: :parties

    validates :name, presence: true
    validate :validate_age 

    private

    def validate_age
        if age == nil || age > 10
            errors.add(:age, 'You should be over 10 years old. Pokemon trainers get their first pokemon when they turn 10.')
        end
    end
end

app/models/type.rb
class Type < ApplicationRecord

    def self.get_type_data
        types_list = RestClient.get 'https://pokeapi.co/api/v2/type'
        types_array = JSON.parse(types_list)["results"]
        types_array.each do |type|
        #Name and URL
            type = Type.create(name: type["name"], url: type["url"])
        end
        self.all.each do |type|
            type_page = RestClient.get(type.url)
            type_info = JSON.parse(type_page)
    
            #WEAK TO
            #2x damage from
            double_damage_from = ""
            type_info["damage_relations"]["double_damage_from"].each do |type|
                double_damage_from = double_damage_from + type["name"] + " "
            end
            type.update(double_damage_from: double_damage_from)

            #half_damage_to
            half_damage_to = ""
            type_info["damage_relations"]["half_damage_to"].each do |type|
                half_damage_to = half_damage_to + type["name"] + " "
            end
            type.update(half_damage_to: half_damage_to)

            #STRONG AGAINST
            #2x damage to
            double_damage_to = ""
            type_info["damage_relations"]["double_damage_to"].each do |type|
                double_damage_to = double_damage_to + type["name"] + " "
            end
            type.update(double_damage_to: double_damage_to)

            #half_damage_from
            half_damage_from = ""
            type_info["damage_relations"]["half_damage_from"].each do |type|
                half_damage_from = half_damage_from + type["name"] + " "
            end
            type.update(half_damage_from: half_damage_from)

            #INEFFECTIVE
            #no_damage_from
            no_damage_from = ""
            type_info["damage_relations"]["no_damage_from"].each do |type|
                no_damage_from = no_damage_from + type["name"] + " "
            end
            type.update(no_damage_from: no_damage_from)

            #no_damage_to
            no_damage_to = ""
            type_info["damage_relations"]["no_damage_to"].each do |type|
                no_damage_to = no_damage_to + type["name"] + " "
            end
            type.update(no_damage_to: no_damage_to)
        end    
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        @trainer = Trainer.first
    end
end

app/controllers/parties_controller.rb
class PartiesController < ApplicationController
    def new
        @party = Party.new
    end

    def create
        @party = Party.new(party_params)
        if @party.save
            redirect_to party_path(@party)
        else
            render :new
        end
    end

    def show
        @party = Party.find(params[:id])
    end

    def index
        @parties = Party.all
    end

    def edit
        @party = Party.find(params[:id])
    end

    def update
        @party = Party.find(params[:id])

        if @party.update(party_params)
            redirect_to parties_path
        else
            render :edit
        end
    end

    def destroy
        @party = Party.find(params[:id])
        @party.destroy
        redirect_to parties_path
    end

    private

    def party_params
        params.require(:party).permit(
            :name,
            :trainer_id,
            pokemon_ids:[]
        )
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def new
        @pokemon = Pokemon.new
        @species = Species.all
    end

    def create
        if Pokemon.create_pokemon(pokemon_params(:nickname, :species_id))
            redirect_to pokemons_path
        else
            render :new
        end
    end

    def index
        @pokemons = Pokemon.all
    end

    def edit
        @pokemon = Pokemon.find(params[:id])
    end

    def update
        @pokemon = Pokemon.find(params[:id])
        if @pokemon.update(pokemon_params(:nickname, party_ids:[]))
            redirect_to pokemon_path(@pokemon)
        else
            render :edit
        end
    end

    def show
        @pokemon = Pokemon.find(params[:id])
    end

    def destroy
        @pokemon = Pokemon.find(params[:id])
        @pokemon.destroy
        redirect_to pokemons_path
    end

    private

    def pokemon_params(*args)
        params.require(:pokemon).permit(*args)
    end
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def new
        @trainer = Trainer.new
    end

    def create 
        @trainer = Trainer.new(trainer_params)

        if @trainer.valid?
            @trainer.save
            redirect_to trainer_path(@trainer)
        else
            render :new
        end
    end

    private

    def trainer_params
        params.require(:trainer).permit(:name, :age)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/party_helper.rb
module PartyHelper
end

app/helpers/pokemon_helper.rb
module PokemonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniLab</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parties/edit.html.erb
<h1>Edit Your Pokemon Party</h1>
<p>Change up to 6 Pokemon</p>

<%= form_for(@party) do |f| %>

    <label>Party Name:</label>
    <%= f.text_field :name %><br>

    <label>Trainer Name:</label>
    <%= collection_select(:party, :trainer_id, Trainer.order(:id), :id, :name, include_blank: true) %><br>

    <label>Pokemon 1:</label>
    <%= collection_select(:party, :pokemon1_id, Pokemon.order(:id), :id, :nickname, include_blank: false) %><br>

    <%= f.submit %>
<% end %>

app/views/parties/index.html.erb
<h1>Pokemon Parties</h1>

<% @parties.each do |party| %>
    <p><%= link_to party.name, party_path(party) %></p>
<% end %>

app/views/parties/new.html.erb
<h1>Create a New Pokemon Party</h1>

<%= form_for(@party) do |f| %>

    <label>Party Name:</label>
    <%= f.text_field :name %><br>

    <label>Trainer Name:</label>
    <%= collection_select(:party, :trainer_id, Trainer.order(:id), :id, :name, include_blank: true) %><br>

    <label>Select 6 Pokemon:</label>
    <%= collection_check_boxes(:party, :pokemon_ids, Pokemon.all, :id, :nickname) %><br>

    <%= f.submit %>
<% end %>

app/views/parties/show.html.erb
<h1><%= @party.name %></h1>

<p>
Pokemon: <%= @party.pokemons.map(&:nickname).join(", ") %>
</p>

<%= link_to "All Parties", parties_path %><br>
<%= link_to "Edit Party", edit_party_path(@party) %><br>
<%= link_to "Delete Party", @party, method: :delete, data: { confirm: "Delete Party permanently?" } %>

app/views/pokemons/edit.html.erb
<h1>Edit Pokemon</h1>

<%= form_for(@pokemon) do |f| %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %></br>

    <%= f.submit %>
<% end %>

app/views/pokemons/index.html.erb
<h1>My Pokemon</h1>
<% @pokemons.each do |pokemon| %>
    <%= link_to pokemon.nickname, edit_pokemon_path(pokemon) %> - <%= pokemon.species.name.capitalize %>: <%= pokemon.type_1 %> <%= pokemon.type_2 %><br/>
<% end %>

<%= link_to "Create Pokemon", new_pokemon_path %>

app/views/pokemons/new.html.erb
<h1>Choose Your Pokemon</h1>

<%= form_for(@pokemon) do |f| %>
    <%= f.label :nickname %>
    <%= f.text_field :nickname %><br>

    <label>Species</label>
    <%= collection_select(:pokemon, :species_id, Species.all, :id, :name) %><br>

    <%= f.submit %>
<% end %>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.nickname.capitalize %> Info</h1>
<p>Species: <%= @pokemon.species.name.capitalize %></p><br>
<p>Types: <%= @pokemon.type_1.capitalize %> <%= @pokemon.type_2 %></p><br>
<%= link_to "Edit Pokemon", edit_pokemon_path(@pokemon) %><br>
<%= link_to "All Pokemon", pokemons_path %><br>
<%= link_to "Delete Pokemon", @pokemon, method: :delete, data: { confirm: "Say Goodbye to your buddy?" } %>

app/views/trainers/new.html.erb
<h1>New Trainer</h1>

<%= form_for(@trainer) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br/>

    <%= f.label :age %>
    <%= f.number_field :age %><br/>

    <%= f.submit %>
<% end %>